TKM_CENTRE_FOR_HIGHER_LEARNING/Controllers/ReportController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TKM_CENTRE_FOR_HIGHER_LEARNING.Models;
using static TKM_CENTRE_FOR_HIGHER_LEARNING.MvcApplication;

namespace TKM_CENTRE_FOR_HIGHER_LEARNING.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        [NoDirectAccess]
        public ActionResult List()
        {            
            Course_Dal obj = new Course_Dal();
            obj.CourseList = new SelectList(obj.Course_List(), "course_id", "course_name");
            TempData["course_list"] = obj.CourseList;            
            return View("ReportStudentFeeList");
        }
        [NoDirectAccess]
        [HttpPost]
        public ActionResult Submit(ReportStudentFee feeModel)
        {
            int id = feeModel.Course_Id;
            var queryString = JsonConvert.SerializeObject(feeModel);
            var uri = WebUtility.UrlEncode(queryString);
            return Redirect("/Reports/Pages/FeeReport.aspx?feeModel="+ uri + "");
        }       
        public ActionResult StudentDetailsSubmit(ReportStudentModel studentModel)
        {
            int id = studentModel.Course_Id;
            var queryString = JsonConvert.SerializeObject(studentModel);
            var uri = WebUtility.UrlEncode(queryString);
            return Redirect("/Reports/Pages/StudentDetailsReport.aspx?studentModel=" + uri + "");
        }
        public ActionResult StudentDetails ()
        {
            Course_Dal obj = new Course_Dal();
            obj.CourseList = new SelectList(obj.Course_List(), "course_id", "course_name");
            TempData["course_list"] = obj.CourseList;
            return View("ReportStudentDetails");
        }

        public ActionResult IncomeExpense()
        {
            Payment_Category_DAL objDal = new Payment_Category_DAL();

            //List<SelectListItem> items = new List<SelectListItem>();
            //items.Add(new SelectListItem() { Text = "All", Value = "0" });
            //items.Insert(items.Count, new SelectListItem { Text = "Others", Value = items.Count.ToString() });

            TempData["temp_payment_Category_list"] = new SelectList(objDal.payment_Category_list(), "payment_category_id", "category_name");
            return View("IncomeExpense");
        }
        public ActionResult IncomeExpenseSubmit(ReportExpenseModel expenseModel)
        {            
            var queryString = JsonConvert.SerializeObject(expenseModel);
            var uri = WebUtility.UrlEncode(queryString);
            return Redirect("/Reports/Pages/IncomeExpenseReport.aspx?expenseModel=" + uri + "");
        }

        public ActionResult Salaryprocessing()
        {
            staff_Dal objDal = new staff_Dal();
            TempData["temp_staff_list"] = new SelectList(objDal.staff_List(), "staff_id", "staff_name");

            ViewBag.Months = new SelectList(Enumerable.Range(1, 12).Select(x =>
             new SelectListItem()
             {
                 Text = CultureInfo.CurrentCulture.DateTimeFormat.AbbreviatedMonthGenitiveNames[x - 1] + " (" + x + ")",
                 Value = x.ToString()
             }), "Value", "Text");



            ViewBag.Years = new SelectList(Enumerable.Range(DateTime.Today.Year, 20).Select(x =>

               new SelectListItem()
               {
                   Text = x.ToString(),
                   Value = x.ToString()
               }), "Value", "Text");

            return View("ReportSalarylist");
        }


        
        public ActionResult SalaryprocessingSubmit(ReportSalaryModel SalaryModel)
        {
            var queryString = JsonConvert.SerializeObject(SalaryModel);
            var uri = WebUtility.UrlEncode(queryString);
            return Redirect("/Reports/Pages/SalaryReport.aspx?salaryModel=" + uri + "");
        }

    }
}

TKM_CENTRE_FOR_HIGHER_LEARNING/Views/Report/IncomeExpense.cshtml
@model TKM_CENTRE_FOR_HIGHER_LEARNING.Models.ReportExpenseModel

@{
    ViewBag.Title = "IncomeExpense";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<div class="card-header">

    <i class="fas fa-table"></i>
    <b>Income Expense Report</b>
</div>
<br />
<div class="container body-content">
    @using (Html.BeginForm("IncomeExpenseSubmit", "Report", FormMethod.Post, new { target = "_blank" }))
    {
        @Html.AntiForgeryToken()
    <div class="form-horizontal">

      <br/>
        <div style="">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div style="">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-row">
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.payment_category_id, htmlAttributes: new { @class = "control-label col-md-7" })
                        <div class="col-md-10">

                            @Html.DropDownListFor(M => M.payment_category_id, (IEnumerable<SelectListItem>)TempData["temp_payment_Category_list"], new { @class = "form-control" })


                            @*@Html.DropDownListFor(M => M.payment_category_id, (IEnumerable<SelectListItem>)TempData["temp_payment_Category_list"], new { @class = "form-control" })*@
                            @*@Html.ValidationMessageFor(model => model.payment_category_id, "", new { @class = "text-danger" })*@
                        </div>
                    </div>

                </div>
                <div class="form-row">
                    <div class="form-group  col-md-6">
                        @Html.LabelFor(model => model.from_date, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.from_date, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.from_date, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group  col-md-6">
                        @Html.LabelFor(model => model.to_date, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.to_date, new { htmlAttributes = new { @Value = @DateTime.Now.ToShortDateString(), @class = "form-control", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.to_date, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-primary" onclick="SelectedIndexChanged()" />
                </div>
            </div>
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/jqueryval")
            @Scripts.Render("~/bundles/jqueryui")
            @Styles.Render("~/Content/cssjqryUi")
            <script type="text/javascript">

                $('#dateselector').datepicker("setDate", new Date(2008, 9, 03));

                $(document).ready(function () {
                    $('input[type=datetime]').datepicker({
                        dateFormat: "m/dd/yy",
                        changeMonth: true,
                        changeYear: true,
                        yearRange: "00:+0"
                    });

                });
            </script>
        }
    </div>
    }

</div>

TKM_CENTRE_FOR_HIGHER_LEARNING/Views/Report/ReportSalarylist.cshtml
@model TKM_CENTRE_FOR_HIGHER_LEARNING.Models.ReportSalaryModel

@{
    ViewBag.Title = "Salary Report";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}
<div class="card-header">
    <i class="fas fa-table"></i>
    <b>staff Salary Report</b>
</div>
<br />
<div class="container body-content">
    @using (Html.BeginForm("SalaryprocessingSubmit", "Report", FormMethod.Post, new { target = "_blank" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <br />
            <div style="">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div style="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.staff_id, htmlAttributes: new { @class = "control-label col-md-7" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(M => M.staff_id, (IEnumerable<SelectListItem>)TempData["temp_staff_list"], new { @class = "form-control" })

                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group  col-md-6">
                            @Html.LabelFor(model => model.month, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.month, (IEnumerable<SelectListItem>
                    )ViewBag.Months, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.month, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group  col-md-6">
                            @Html.LabelFor(model => model.year, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.year, (IEnumerable<SelectListItem>
                   )ViewBag.Years, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-primary" onclick="SelectedIndexChanged()" />
                    </div>
                </div>
            </div>
            @section Scripts {
                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/jqueryval")
                @Scripts.Render("~/bundles/jqueryui")
                @Styles.Render("~/Content/cssjqryUi")
           
            }
        </div>
    }
</div>

TKM_CENTRE_FOR_HIGHER_LEARNING/Views/Report/ReportStudentDetails.cshtml
@model TKM_CENTRE_FOR_HIGHER_LEARNING.Models.StudentModel

@{
    ViewBag.Title = "ReportStudentDetails";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<div class="card-header">

    <i class="fas fa-table"></i>
    <b>Student Fee Report</b>
</div>
<br />

<div class="container body-content">
    @using (Html.BeginForm("StudentDetailsSubmit", "Report", FormMethod.Post, new { target = "_blank" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">


            <div style="">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div style="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.Course_Id, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">

                                @Html.DropDownListFor(M => M.Course_Id, (IEnumerable<SelectListItem>)TempData["course_list"], new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Course_Id, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Semester, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Semester, "", new { @class = "text-danger" })
                            </div>

                        </div>

                    </div>

                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-primary" onclick="SelectedIndexChanged()" />
                    </div>
                </div>
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jquery") 
                @Scripts.Render("~/bundles/jqueryval")
                @Scripts.Render("~/bundles/jqueryui")
                @Styles.Render("~/Content/cssjqryUi")


            }
        </div>
    }

</div>

TKM_CENTRE_FOR_HIGHER_LEARNING/Views/Report/ReportStudentFeeList.cshtml
@model TKM_CENTRE_FOR_HIGHER_LEARNING.Models.ReportStudentFee
@{
    ViewBag.Title = "Report Student FeeList";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<div class="card-header">

    <i class="fas fa-table"></i>
    <b>Student Fee Report</b>
</div>
<br />
<div class="container body-content">
    @using (Html.BeginForm("Submit", "Report", FormMethod.Post, new { target = "_blank" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">


            <div style="">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div style="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.Course_Id, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">

                                @Html.DropDownListFor(M => M.Course_Id, (IEnumerable<SelectListItem>)TempData["course_list"], new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Course_Id, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Semester, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Semester, "", new { @class = "text-danger" })
                            </div>

                        </div>

                    </div>
                    <div class="form-row">
                        <div class="form-group  col-md-6">
                            @Html.LabelFor(model => model.from_date, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.from_date, new { htmlAttributes = new { @class = "form-control" ,autocomplete = "off" } })
                                @Html.ValidationMessageFor(model => model.from_date, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group  col-md-6">
                            @Html.LabelFor(model => model.to_date, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.to_date,  new { htmlAttributes = new { @Value = @DateTime.Now.ToShortDateString(), @class = "form-control" , autocomplete = "off" } })
                                @Html.ValidationMessageFor(model => model.to_date, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-primary" onclick="SelectedIndexChanged()" />
                    </div>
                </div>
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/jqueryval")
                @Scripts.Render("~/bundles/jqueryui")
                @Styles.Render("~/Content/cssjqryUi")

                <script type="text/javascript">

                    $(document).ready(function () {
                        $('input[type=datetime]').datepicker({
                            dateFormat: "m/dd/yy",
                            changeMonth: true,
                            changeYear: true,
                            yearRange: "00:+0"
                        });

                    });
                </script>
                <script type="text/javascript">

                    function SelectedIndexChanged() {
                        //Form post
                        document.demoForm.submit();
                    }
                </script>
            }
        </div>
    }

</div>