TKM_CENTRE_FOR_HIGHER_LEARNING/Models/Entroll.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;

namespace TKM_CENTRE_FOR_HIGHER_LEARNING.Models
{
    public class Entroll
    {
        [Display(Name = "Semester")]
        public int semester { get; set; }
    }
    public class EntrollDAL
    {
        public int entroll_stundent(string Ids)
        {
            int i = 0;
            try
            {

          
            dal_stored_procedure dal_stored_procedure1 = new dal_stored_procedure();
            dal_stored_procedure1.name = "[dbo].[pr_add_student_entrollment]";
            dal_manager dal_manager1 = new dal_manager();
            dal_stored_procedure1.add_parameter("@student_ids", Ids, DbType.String, ParameterDirection.Input);
                dal_stored_procedure1.add_parameter("@return_val", null, DbType.Int32, ParameterDirection.Output);
                dal_manager1.execute_nonquery(dal_stored_procedure1);
             i= (int)dal_stored_procedure1.get_params()["@return_val"].param_value;

            }
            catch (Exception ex)
            {
                i = 0;
                return i;
            }
            finally
            {
               
               
            }
            return i;
        }
    }
}

TKM_CENTRE_FOR_HIGHER_LEARNING/Controllers/EntrollController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TKM_CENTRE_FOR_HIGHER_LEARNING.Models;
using TKM_CENTRE_FOR_HIGHER_LEARNING.ViewModel;

namespace TKM_CENTRE_FOR_HIGHER_LEARNING.Controllers
{
    public class EntrollController : Controller
    {
        EntrollViewModel objStudentModel = new EntrollViewModel();
        StudentDal objDal = new StudentDal();
        Course_Dal obj_course = new Course_Dal();

        // GET: Entroll
        public ActionResult Index()
        {
            List<SelectListItem> listTeam = new List<SelectListItem>();
            listTeam.Add(new SelectListItem());
            obj_course.CourseList = new SelectList(obj_course.Course_List(), "course_id", "course_name");
            TempData["course_list"] = obj_course.CourseList;
           
            objStudentModel.StudentNames = listTeam;
            objStudentModel.vmList = new List<EntrollViewModel>();
            //objDal.GetAllStudentList();


            return View(objStudentModel);

          

            
        }

       
        public ActionResult LoadStudent(EntrollViewModel vm)
        {            


            objStudentModel = objDal.GetAllStudentList(vm);

            
          //  string strDDLValue = Request.Form["course.course_id"].ToString();

            obj_course.CourseList = new SelectList(obj_course.Course_List(), "course_id", "course_name");
            TempData["course_list"] = obj_course.CourseList;
            return View("Index",objStudentModel);

        }
        [HttpPost]
        public ActionResult EntrollStudent(string Name)
        {

            EntrollDAL obj = new EntrollDAL();
            if (obj.entroll_stundent(Name)==1)
            {
                 return Json(new { success = Name });
            }
            else
            {
                return Json(new { success = Name });
            }
           
        }
    }
}

TKM_CENTRE_FOR_HIGHER_LEARNING/Views/Entroll/Index - Copy.cshtml
@model TKM_CENTRE_FOR_HIGHER_LEARNING.ViewModel.EntrollViewModel
@{
    ViewBag.Title = "Create New Staff";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

@*<script src="~/Scripts/jquery-1.7.1.min.js"></script>*@
<script src="~/vendor/jquery/jquery.min.js"></script>
<link href="~/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script>

    $(document).ready(function () {
        $('.chkclass').click(function () {

            var getchkid = $(this).attr('id');
            var isChecked = $('#' + getchkid).is(':checked');

            if ($('#' + getchkid).is(':checked') == true) {
                // $('#td' + $(this).val()).css("color", "white");
                //   $('#td' + $(this).val()).addClass(" list-group-item-success");
            }
            else {
                //  $('#td' + $(this).val()).css("color", "black");
                // $('#td' + $(this).val()).css("background-color", "white");
            }
        });

        $('#bttn_Click').click(function () {

            var studentListVal = null;
            studentListVal = [];

            $('input:checkbox:checked').each(function () {
                studentListVal.push($(this).attr('value'));
            });

            $.ajax({
                type: "post",
                url: "/Entroll/EntrollStudent",
                data: { Name: studentListVal },
                datatype: "json",
                traditional: true,
                success: function (data) {

                    var selectedIds;
                    for (var i = 0; i < data.success.length; i++) {
                        if (selectedIds != undefined) {
                            selectedIds = selectedIds + " " + data.success[i];
                        }
                        else {
                            selectedIds = data.success[i];
                        }
                    }
                    alert('You have Selected Student Ids- ' + selectedIds);
                }
            });

        });

    });

</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
       

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-row alert alert-info">
           @using (Html.BeginForm("LoadStudent", "Entroll", FormMethod.Post))
           {
            <div class="form-group col-md-5">
                @Html.LabelFor(model => model.course.course_name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.course.course_id, (IEnumerable<SelectListItem>)TempData["course_list"], new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.course.course_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group col-md-3">
                @Html.LabelFor(model => model.entroll.semester, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.entroll.semester, new { htmlAttributes = new { @class = "form-control", @maxlength = "1" } })
                    @Html.ValidationMessageFor(model => model.entroll.semester, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-4" style="align-self: center;margin-top: 14px;">
                <div class="">
                    <input type="submit" value="View Student" class="btn btn-success"  />
                    @Html.ActionLink("Back to List", "LoadStudent")
                   
                </div>

                </div>
           }
</div>

</div>
}



                <div id="list-group" style="height: 400px; overflow: auto; width:350px;">
                    @foreach (var names in @Model.StudentNames)
                    {
                        var checkBoxId = "chk" + names.Value;
                        var tdId = "td" + names.Value;
                        <table width="100%" class="list-group list-group-flush">
                            <tr class="list-group-item">
                                <td>
                                    <input type="checkbox" id="@checkBoxId" class="chkclass" value="@names.Value" />
                                </td>
                                <td id="@tdId">
                                    @names.Text
                                </td>
                            </tr>

                        </table>
                    }
                </div>

                <div>
                    <input type="button" id="bttn_Click" value="Send Checked value to Controller" />
                </div>

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>


                @*https://www.c-sharpcorner.com/UploadFile/sourabh_mishra1/checkboxlist-in-Asp-Net-mvc/*@

<script>
function redirectOnClick(){
    document.location = 'Entroll/LoadStudent';
}
</script>